### PR TITLE
Reformat default server.fs - use DI

### PR DESCRIPTION
**Pull request by isaacabraham**
Keeps the class-based structure, but makes the following changes:

* Move the initialisation of the in-memory DB into the Storage class.
* Registration of the service as a singleton into ASP .NET service collection.
* Retrieval of the service through the Http Context's `GetService` method.
* Small formatting changes.

### CODE REVIEW

**Comment by olivercoad** [comment]
I'm guessing you're choosing between these two PRs. I like #465. This one would be great as a recipe for how to use DI.

**Comment by isaacabraham** [comment]
@olivercoad exactly. And yes, my preference is the other one too :-)

**Comment by theimowski** [comment]
not sure which one I prefer TBH :) need to give it some more thoughts

**Comment by isaacabraham** [comment]
I suggest we close this and convert into a recipe / guide for DI with SAFE Stack.

**Comment by isaacabraham** [comment]
Closing this - one of us will create a recipe explaining the basics of DI within the context of the server-side SAFE Stack components.

**Comment by isaacabraham** [comment]
cc: @Ryan-Palmer-CIT @theprash @Akash-Mair

**Pull request closed without merging**
