### PR TITLE
Set font by customizing a Bulma variable

### PR DESCRIPTION
**Pull request by kerams**
Now that Bulma is part of the bundle, it's possible to customize any of its variables before we import it, so there's no need for CSS in this particular case.

### CODE REVIEW

**Comment by kerams** [comment]
It might be useful to also have this link https://bulma.io/documentation/customize/variables/ in a comment there

**Comment by kerams** [comment]
Is it the newline that breaks the build or what?

**Comment by theimowski** [comment]
probably - I've seen that before, not sure why this happens. Can you revert whitespace changes?

**Comment by kerams** [comment]
Looks good now.

**Comment by theimowski** [comment]
thanks!

**Pull request merged**
