### PR TITLE
Run paket restore/install based on existence of paket.lock file

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**

### CODE REVIEW

**Comment by theimowski** [comment]
I don't think it's good idea to trigger `paket install` on every build. Ideally we'd trigger `paket install` after the template is created, but not yet sure how to achieve that

**Comment by Zaid-Ajaj** [comment]
Solved, see last commit :smile:

**Comment by Zaid-Ajaj** [comment]
@theimowski I just checked, ionide with vscode actually restores the packages right away when you open the project repo

**Comment by theimowski** [comment]
Awesome - makes things simple. Added same to `build.cmd` and released in 0.4.2, thanks

**Pull request merged**
