### PR TITLE
[WIP] Extract common FAKE build script logic into a separate NuGet package

### PR DESCRIPTION
**Pull request by theimowski**
The idea here is to take common logic from SAFE apps build scripts and put it into a NuGet package.
Of course we need the helper functions to be configurable.
Thanks to this, the initial build script can be much simpler and example SAFE apps in SAFE-Stack org can use the same logic.

Also, this allows for better support, e.g. in case there is some new idea for a build script enhancement, such a feature can be released as part of the package, and those using the package (e.g. from SAFE template) can easily consume that feature.

I started using the initial NuGet package in following repositories, to see how the usage would look like:
* [SAFE-BookStore](https://github.com/theimowski/SAFE-BookStore/blob/safe-build/build.fsx)
* [SAFE-ConfPlanner](https://github.com/theimowski/SAFE-ConfPlanner/blob/safe-build/build.fsx)
* [SAFE-Chat](https://github.com/theimowski/SAFE-Chat/blob/safe-build/build.fsx) - it's best visible here, as there is currently no FAKE script in SAFE-Chat

For all 3 apps this allows to run `fake build -t run` to enter the interactive mode.
The testing was done locally - NuGet package is not yet published

Feedback very welcome
/cc @forki @matthid @isaacabraham @Krzysztof-Cieslak @Zaid-Ajaj @OlegZee @rommsen

### CODE REVIEW

**Comment by isaacabraham** [comment]
Nice! Just a couple of questions / comments before I actually try this out.

1. Is there any reason why we *shouldn't* move to a NuGet package for the SAFE deployment elements? I'm just trying to think through all the pros / cons here. Pros sounds like we can relatively easily start to do in-place updates (as long as we keep the interface the same) which is great. Is there any chance that moving to a NuGet package will slow down things / reduce our ability to quickly put in changes etc.?

2. I'm not a fan of copying across the ARM Template deployment code - we make changes to that every so often to upgrade it in the original CIT repo, and I don't fancy maintaining it in two places. Why not keep that as a git dependency and then push it out in the NuGet package?

**Comment by matthid** [comment]
I think it is kind of hard to get the api of the nuget package “right”. The problem is not only about deduplicating code but getting into the ecosystem (make it easy for newcomers) and tweaking stuff. This is harder when there is a new package as you now have to learn another thing which potentially builds on top of something you have to learn as well...

In principle I think there is potential for a package here butwe should take some time about getting the api correct and some time about discussing what problem exactly we are trying to solve here...

**Comment by isaacabraham** [comment]
@matthid That's my fear as well. Perhaps we could start in a more lightweight fashion - just a dedicated file containing the modules that would eventually go into the package? Or as a git file?

**Comment by theimowski** [comment]
@isaacabraham - answering your question:

1. The only drawback I can see is related to what @matthid mentioned - an interface which tries to do "too much"

2. I was having some issue with the github reference when creating NuGet package, which I didn't take time to investigate. If the dependency works fine, I'm ok with removing the copy.

The biggest win here IMO would be keeping in sync SAFE template and example apps. There has already been a number of cases where a PR was sent to Bookstore with a change that should be also in the template. Having such changes centralised in a NuGet package means more coherent stack.

For a more lightweight start we could make it a GitHub dependency - the module itself has nuget dependencies, so we could attach it to existing SAFE apps this way.

**Comment by theimowski** [comment]
Agreed, we can make this work later. Closing until further notice

**Comment by isaacabraham** [comment]
@theimowski can you put an "on-hold" label or similar on this one - I think this is definitely something we would want to have, as the benefits are very good to help people keep up-to-date as and when we release new stuff.

**Comment by theimowski** [comment]
There you go

**Pull request closed without merging**
