### PR TITLE
Upgrate thoth fetch to version 2

### PR DESCRIPTION
**Pull request by robertpi**

### CODE REVIEW

**Comment by isaacabraham** [comment]
Does this not need all the lock files updated as well? @theimowski 

Also - not sure if at this stage we will make anything other than support hotfixes to the v1 template given that v2 is right around the corner.

**Comment by isaacabraham** [comment]
But we should definitely use the work you've done here in the v2 template!

**Comment by theimowski** [comment]
Yup, it does require updating lock files (`fake build -t UpdatePaketLockFiles -- Client`)
I'll submit a separate PR that does it. 
#353 is related

**Comment by theimowski** [comment]
Closing in favour of #356

**Pull request closed without merging**
