### PR TITLE
Net6 + Saturn test

### PR DESCRIPTION
**Pull request by teknikal-wizard**
This is just [tico321](https://github.com/tico321) 's PR with more deps updated including the latest Saturn preview pulled in, plus the dotnet tools bumped. 

I mainly created it as I am trying to find out what is breaking the build pipeline and I'm not a maintainer so I needed my own branch to tweak and push. It can be absorbed back into the original PR once I have (hopefully) fixed it.

### CODE REVIEW

**Comment by olivercoad** [comment]
I think I found the issue.

https://github.com/CompositionalIT/SAFE-template/blob/6156f9bf287eabdeab02978cb4bef6fc7837e9f3/tests/Tests.fs#L151-L160

It is doing the `dotnet run` before the `dotnet tool restore`.
Moving line 160 to 153 fixes it.

**Comment by Ryan-Palmer-CIT** [comment]
Just pushing it up now to test, thanks!

**Comment by Ryan-Palmer-CIT** [comment]
@olivercoad  it passed, amazing, thank you :) Still seems odd that it worked locally and on the other build hosts.

**Comment by olivercoad** [comment]
Awesome! Yeah that's odd. I know these kinds of ci issues can sometimes take hours to diagnose, so glad it works now.

**Comment by theimowski** [comment]
Now this PR has just the azure check but it's missing the Travis ones 😞 need to figure out why that is

**Comment by theimowski** [comment]
Ok Travis now back, but don't know of a way to re-run it for this PR, so created a duplicate here #513 - once it turns green, I'm good with getting this merged and released. @isaacabraham you fine with that?

**Comment by teknikal-wizard** [comment]
Just updated Saturn to the full release (along with some other bits), so we have no preview dependencies now.

**Comment by teknikal-wizard** [comment]
Both pipelines seem to be happy as well.

**Comment by isaacabraham** [comment]
@theimowski i'm good with all this, let's do it.

**Comment by isaacabraham** [comment]
@theimowski I'm going to merge this tomorrow unless I hear otherwise :-) Perhaps we can push a new release out next week?

**Comment by theimowski** [comment]
sure, go for it 👍  sorry last weeks were a bit hectic for me, I'm happy to share push access to nuget should you want to release it as well.

**Comment by theimowski** [comment]
Just released it in version [4.0.0](https://www.nuget.org/packages/SAFE.Template/4.0.0)

**Pull request merged**
