### PR TITLE
Update Fantomas to 4.6

### PR DESCRIPTION
**Pull request by nojaf**

### CODE REVIEW

**Comment by theimowski** [comment]
Funny coincidence - I was just reviewing 4.6 release notes :) 
Any idea why all CI tasks failed with same error?

```
client: Bundling for production...
client: [webpack-cli] Failed to load '/home/travis/build/SAFE-Stack/SAFE-template/Content/default/webpack.config.js' config
client: [webpack-cli] TypeError: MiniCssExtractPlugin is not a constructor
client:     at Object.<anonymous> (/home/travis/build/SAFE-Stack/SAFE-template/Content/default/webpack.config.js:88:13)
...
```

master branch builds fine - as you changed only *.fs files I'd guess this could be related to some nasty spacing / line ending issue with Fable?

**Comment by nojaf** [comment]
Hmm, this feels very unrelated to be honest. I would need to take a closer look as I'm on my phone right now. Who still uses webpack though 😅

**Comment by nojaf** [comment]
Tried this locally, I get the exact same webpack error with the master branch as with this PR.
I also noticed the `package-lock.js` is updated when I run `dotnet run -- Bundle` inside the `default` folder.
I find this weird.

**Comment by nojaf** [comment]
Turns out my branch was out of sync 🙈

**Comment by theimowski** [comment]
cool, thanks!

**Pull request merged**
