### PR TITLE
Hide project / output / cache files from VS Code

### PR DESCRIPTION
**Pull request by jwthomson**
Relates to #617.

After some discussion we thought that ignoring some files is a good idea, but hiding files as a tree under other files could be confusing. Most of the files which were proposed for hiding in a tree were config files which are more likely to need to be edited so we opted not to nest them.

### CODE REVIEW

**Comment by isaacabraham** [comment]
@jwthomson is this good to go?

**Review by Larocceau — CHANGES_REQUESTED** [review]
check if this can be done with the gitignore instead

**Comment by Larocceau** [comment]
@isaacabraham, no; we later decided to see if we can use the gitignore for this. I redacted my approval

**Comment by jwthomson** [comment]
There were some files which are ignored in the `.gitignore` which someone may wish to edit from within VS code, e.g. user-specific settings files. So I opted **not** to persue using the `.gitignore` file as a basis for what files should be hidden.

**Review by Larocceau — APPROVED** [review]

**Pull request merged**
