### PR TITLE
lowercased parameters and updated sources

### LINKED ISSUE #57: make the parameters lower-case
Seems the convention is to use lower-case parameter names for dotnet templates.

### PR DESCRIPTION
**Pull request by CallumVass**
Resolves #57

### CODE REVIEW

**Comment by theimowski** [comment]
Thanks for contributing, 
Can you please also have a look at other files using the parameters, i.e. `*.fs`, `*.fsproj`, `*.fsx`, `paket.*`, `index.html`?

**Comment by isaacabraham** [comment]
Perhaps a separate PR but is it worth also redoing the NPM argument as -packagemanager either as yarn or NPM?

**Comment by isaacabraham** [comment]
Yes fine, don't mind what it's called ??
________________________________

**Comment by theimowski** [comment]
Looks good! Thanks

**Pull request merged**
