### PR TITLE
use FAKE's new CreateProcess API

### PR DESCRIPTION
**Pull request by vilinski**
Hi,

already applied this changes to [fantomas-ui](https://gitlab.com/jindraivanek/fantomas-ui/commit/e6ff5562b723a8a5e56348849e0525bc201c1ab1) repo, created from SAFE template.

The `Tests` target is failing for me. Didn't understand how to properly update FAKE within Content.
After running `UpdatePaketLockFiles` the `Tests` are hanging infinitely.

### CODE REVIEW

**Comment by theimowski** [comment]
Hi, thanks for PR
To run `UpdatePaketLockFiles` just for the Build group: `fake build -t UpdatePaketLockFiles -- Build` 

The `Tests` target by default generates 20 test cases which may take around 30mins to complete. If you want to run tests with less cases you can set environment variable, e.g.: `MAX_TESTS=3 fake build -t Tests`

**Comment by theimowski** [comment]
Did you rebase on newest master? Why the diff shows so many changes?

**Comment by theimowski** [comment]
Yes please, I've run `UpdatePaketDependencies` yesterday, so it should already be using newest Fake libraries

**Comment by vilinski** [comment]
closing in favor of #169

**Pull request closed without merging**
