### PR TITLE
Net6

### PR DESCRIPTION
**Pull request by tico321**
Update the minimal and the default templates to .net6 as well as the template solution.

Note: Travis and Azure DevOps tasks are yelling that the version of .Net is not the correct one. I updated all the configurations that I found in the repository so I'm thinking it's something that needs to be updated directly in Travis and Azure. I'm going to need someone to help me do that.

### CODE REVIEW

**Comment by theimowski** [comment]
For Travis, Linux build succeeded: https://app.travis-ci.com/github/SAFE-Stack/SAFE-template/jobs/551883475, it's just mac build failing: https://app.travis-ci.com/github/SAFE-Stack/SAFE-template/jobs/551883476 - logs show mac is trying to download a file from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/dotnet-sdk-6.0-osx-x64.pkg which doesn't exist. I'd try specifying whole SDK version `6.0.101` in travis.yml.

For Azure Pipelines, someone from Compositional IT would need to take a look @isaacabraham

**Comment by theimowski** [comment]
@isaacabraham do you have any update on Azure Pipelines configuration here?

**Comment by theimowski** [comment]
https://github.com/SAFE-Stack/docs/issues/249 talks about why want to wait for SDK 6.0.200 to be released

**Comment by tico321** [comment]
Thank you for the update.

**Comment by isaacabraham** [comment]
@theimowski I'm just looking into this - not sure what's happened here because builds do seem to be running on some occasions.

**Comment by Ryan-Palmer-CIT** [comment]
Hi all! @isaacabraham and I have been trying to work out why devops is failing. Paket restore fails but we can't see why it is happening. It is almost certainly a build host issue as it is passing linux + macos on Travis, and builds fine on our local Windows machines. It is just the Devops ubuntu host that is acting strangely.

@forki Isaac suggested I tag you in case you might be able to provide some insight.

@tforkmann I made a branch from this PR to include Saturn prerelease if you want to give it a go, works fine other than this failing devops issue - #506

**Comment by Ryan-Palmer-CIT** [comment]
Good news! Thanks to @olivercoad we have fixed the build over in #506  . @tico321 , would you like to merge that branch into this one and then I'll abandon my PR. Cheers :)

**Comment by tico321** [comment]
@Ryan-Palmer-CIT that's great!! And I see that you have all the changes required for the minimal and the default template, so I don't see a reason to drop mine? or do I have some changes that you need?
Also, your branch comes from the CompositionalIT repo and since it's not a SAFE-Template branch it's going to be harder to merge it.

**Comment by Ryan-Palmer-CIT** [comment]
@tico321  yeah we can take mine, that's fine. Just didn't want to pinch your contribution! Thanks for getting us 90% of the way :)

**Pull request closed without merging**
