### PR TITLE
Add Shared.fsproj

### PR DESCRIPTION
**Pull request by theprash**
See #255.

### CODE REVIEW

**Comment by theimowski** [comment]
Thanks!

**Comment by iNecas** [comment]
FYI this seemed to break the template, at least on my Linux machine https://github.com/SAFE-Stack/SAFE-template/issues/258

**Comment by theimowski** [comment]
Had to revert the change
It broke on my Mac as well - the fix was to clear fable caches (.fable directory)
We need to make it work in all scenarios

**Comment by theimowski** [comment]
@theprash  any chances you can have another look at this? would be nice to have it

**Pull request merged**
