### PR TITLE
Add Heroku support

### PR DESCRIPTION
**Pull request by Nhowka**
Implements #136 

I'm using `https://github.com/SAFE-Stack/SAFE-buildpack` as a placeholder. I created a [branch](https://github.com/Nhowka/dotnetcore-buildpack/tree/SAFE) on my modified buildpack for supporting it. You can change it to `https://github.com/Nhowka/dotnetcore-buildpack#SAFE` if you don't want to have it under the org name.

I also had to change the `--port free` position because it wasn't being recognized. Weird.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Will this not install `dotnet` twice? once by the build pack to be able to globally install `fake-cli` and once again from inside `build.fsx`?

**Comment by Nhowka** [comment]
Yes. Using specific version it failed, but didn't when set to the default.

Help me! How do I use the existing version?

**Comment by Zaid-Ajaj** [comment]
Which specific version did you use and why did it fail? if you choose version 2.1.300 from the build pack, it should be good enough to install the fake-cli and you can delete the dotnet (re)installation from the build.fsx, this operation of installing dotnet from build.fsx was already giving lots of headaches for local dev as it creates and locks a global.json file after restarting the app

**Comment by Nhowka** [comment]
It fails because of dependencies. If I remember correctly it was `libunwind`. I tried some stuff and that clearly shows that I don't know what I'm doing.

**Comment by Nhowka** [comment]
It's probably ready, now. I created [this repo](https://github.com/Nhowka/safe-buildpack) with a cleaner version of the buildpack. I can transfer the ownership of it.

**Comment by Nhowka** [comment]
Nope, other test failed on my fork. The tests are being very random...

**Comment by theimowski** [comment]
The tests are random on purpose - the number of all possible combinations for template options is too big, so I'm using FsCheck generator to choose 10 various set of options, they'll be different each time. If 10 is not big enough we can increase it

**Comment by Nhowka** [comment]
With those files it is just pushing to the Heroku git, there is a guide here: https://devcenter.heroku.com/articles/git

I will transfer the ownership of the buildpack now.

**Comment by theimowski** [comment]
Thanks, I'll test that in coming days

**Comment by Nhowka** [comment]
I checked and it's creating the `Procfile` with the wrong base, I'll try to fix it.

**Comment by theimowski** [comment]
I also got a request from GitHub:

`@Nhowka wants to transfer the Nhowka/SAFE-buildpack repository to theimowski/SAFE-buildpack`

I think you wanted to move to `SAFE-Stack/SAFE-buildpack` instead? 
Is it ok to add that repository to org? @SAFE-Stack/sample-app-admins

**Comment by Nhowka** [comment]
Yes, I couldn't transfer to the org. Feels like the bundle target didn't created the deploy folder, probably the Procfile should be in the ignore list too. It's like the buildpack never ran.

**Comment by theimowski** [comment]
I think that `bundle` target creates the `deploy` dir, but it's gitignored - should it be pushed to heroku remote?

**Comment by Nhowka** [comment]
Yes, that means that the buildpack didn't work. Did you changed the path on `app.json` to the real repository?

**Comment by theimowski** [comment]
yes, changed it to https://github.com/Nhowka/SAFE-buildpack

**Comment by Nhowka** [comment]
So probably it won't add a new buildpack to an already created project, just to projects that are being created from the repository. I'll add a new target that configures the buildpack into the current repository.

**Comment by theimowski** [comment]
@Nhowka do you have any update to this?

**Comment by Nhowka** [comment]
My main machine stopped working, I'll try to revisit that on the weekend on another machine. The progress I had before that was about adding some confirmation of the existence of the heroku cli and checking if the folder already was part of a heroku project or not. Probably a new target just for initing the project and adding the buildpack will need to run once before being able to deploy.

**Comment by andrzejsliwa** [comment]
@Nhowka any progress on it?

**Comment by Nhowka** [comment]
I got some free time and a working machine. I did some tests updating the buildpack and got another heroku-based project to start fine without needing mono using paket as a global tool. That simplifies a lot.

 I'll keep this PR open to use as reference, but probably I'll need to create a new PR with a new branch. Unless some git guru show me the right way to bring these changes to the current version with less work.  😋

**Comment by Nhowka** [comment]
Use #251.

**Pull request closed without merging**
