### PR TITLE
Generate paket.lock for all possible template options

### PR DESCRIPTION
**Pull request by theimowski**
The idea here is to write couple of Fake helper targets for dealing with various paket.lock files in the template.
Because the paket.lock will always have 3 groups:
* Build
* Client
* Server

we can treat each of the group separately to minimize total number of paket.lock permutations.

Workflow in this PR for working with paket.lock

* `GenPaketLockFiles` Fake target can generate lock files for representative number of template options, split it for each group and save in `./Content/{Group}` directory
* `BuildPaketLockFiles` can take the lock files from corresponding `./Content/{Group}` dirs and build all permutations of lock files in `./Content`. This target is now dependency of `Pack` target
* `RemovePaketLockFiles` occurs after `Pack` target so that the git repo is not littered with generated paket.lock files
* `GenJsonDefinitions` target can be invoked to print conditions needed to be placed into `template.json` manifest
* `UpdatePaketLockFiles` updates all paket lock files (can pass in specific group name(s) as target parameter)

Refers to #66

### CODE REVIEW

**Comment by isaacabraham** [comment]
Looks very interesting! Will this generate the lock files in advance or when people create a new project from the template?

**Comment by theimowski** [comment]
it creates the lock files before packaging up the NuGet, so they are present in the template already

**Comment by isaacabraham** [comment]
How many are there currently?

**Comment by theimowski** [comment]
```
type ServerPaketDependencies =
    { Server : ServerPaketDependency
      Remoting : bool
      Azure : bool }

type CombinedPaketDependencies =
    { Azure : bool
      Remoting : bool
      Fulma : bool
      Server : ServerPaketDependency }
```

3 x 2 x 2 x 2 = **24**

**Pull request merged**
